### ISSUE TITLE
Possible icon that starts fake windows update

### ISSUE THREAD

**Issue by so1maru** [Potato-Development/funstuff#2]
Loading gif, extremely slow percentage, etc.

**Comment by so1maru** [comment]
> Loading gif, extremely slow percentage, etc.

@MysteryFlask

**Comment by MysteryFlask** [comment]
This is a very good idea actually, I will add that to the roadmap shortly!

**Comment by MysteryFlask** [comment]
@edamame-maru check README :)

**Comment by MysteryFlask** [comment]
Icon is added, the functionality is being added now.
